Issue/74–yaml–pipeline file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,65 +1,437 @@
-image: node:8
+image: registry.gitlab.com/hybrix/hybrixd/base-images/build-image:stable
+
+variables:
+  GIT_STRATEGY: none
+
+
+stages:
+ - build-deterministic
+ - build-hybrixd
+ - test
+
 
 deterministic:
-  stage: build
+  cache: {}
+  stage: build-deterministic
   script:
-    # install unzip
-    - apt-get update
-    - apt-get install unzip
-    - apt-get install rsync -y
 
-    # trigger pipeline common
-    # - "curl --request POST --form \"token=$CI_JOB_TOKEN\" --form ref=master https://gitlab.com/api/v4/projects/hybrix%2Fhybrixd%2Fcommon/trigger/pipeline"
+    # Because of race conditions with merge squashes leaving broken references we circumvent the default git strategy GIT_STRATEGY: none
+    - cd ..
+    - "git clone -n https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/hybrix/hybrixd/client/modules/deterministic.git --depth 10 --single-branch --branch $CI_COMMIT_REF_NAME"
+    - cd deterministic
+    - if git log | grep $CI_COMMIT_SHA; then
+    -   echo "Commit $CI_COMMIT_SHA exists, retrieving it."
+    -   "git -c advice.detachedHead=false checkout $CI_COMMIT_SHA"
+    - else
+    -   echo "Commit $CI_COMMIT_SHA does not exist, retrieving latest in branch $CI_COMMIT_REF_NAME"
+    -   "git checkout"
+    - fi
+    - cd ..
+    - "git clone -n https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/hybrix/hybrixd/common.git --depth 10 --single-branch --branch master"
+    - cd common
+    -   "git checkout"
+    - cd ..
+    - cd deterministic
 
-    # download [common] artifact
-    - "curl --location --header \"JOB-TOKEN: $CI_JOB_TOKEN\" \"https://gitlab.com/api/v4/projects/hybrix%2Fhybrixd%2Fcommon/jobs/artifacts/master/download?job=common\" -o artifacts-common.zip"
-
-    # remove link to common and unzip the downloaded artifact to the directory (|| true --> on error, no problem)
-    - rm -rf  common || true
-    - unzip -o artifacts-common.zip -d common
-
-    # remove the zip-file (|| true --> on error, no problem)
-    - rm -rf  artifacts-common.zip || true
-
-    # remove symbolic link to node
-    - rm -rf  node_binaries || true
-    # don't download git clone https://github.com/internetofcoins/nodejs-v8-lts.git, refer to docker pre installed nodejs as defined in the first line of this file
-    - "ln -s \"$(which nodejs)\" node_binaries"
-
-    # run the build-script of the interface
+    # compile in release mode (uglified and minified)
     - ./scripts/npm/compile.sh
-    - npmlist=$(npm list --only=prod --depth=0 -json)
-    - set +e
-    - npmaudit=$(npm audit -json)
-    - set -e
+    # For debug use - ./scripts/npm/compile.sh debug
 
-    - ls -l
-
-    # clean up and prepare the artifacts (instead of having a dist)
-    # remove everything except () is extglob syntax, which should be enabled first
+    # extract dist
     - shopt -s extglob
-    - rm -rf !(dist) || true
-    - mv ./dist/* ./
-    - rm -rf ./dist || true
-    - rm -rf ./.git || true
+    - rm -rf !(dist)
+    - dist
 
-    # remove all files starting with a .
-    - find -name ".*" -type f -delete
-
-     # create a .version file
+    # create a .version file
     - timestamp=$(date -u '+%Y-%m-%dT%H:%M:%S+00:00')
-    - if [[ "$DEBUG_ENABLED" == "1"  ]]; then mode=debug; else mode=release; fi
-    - echo "{\"${CI_PROJECT_PATH_SLUG}\":{\"mode\":\"${mode}\", \"project_path\":\"${CI_PROJECT_PATH}\", \"commit_ref_name\":\"${CI_COMMIT_REF_NAME}\", \"commit_ref_slug\":\"${CI_COMMIT_REF_SLUG}\", \"commit_sha\":\"${CI_COMMIT_SHA}\", \"pipeline_url\":\"${CI_PIPELINE_URL}\", \"npm-list\":${npmlist}, \"npm-audit\":${npmaudit}, \"packaged\":\"${timestamp}\"}}" > .version
-
-    - ls -l
-
-    # verification steps
-    - if [ ! -f module.js ]; then echo "module.js not found!"; exit 1; fi
-    - if [ ! -f source.deterministic.json ]; then echo "source.deterministic.json not found!"; exit 1; fi
+    - mode=release
+    - echo "{\"${CI_PROJECT_PATH_SLUG}\":{\"mode\":\"${mode}\", \"project_path\":\"${CI_PROJECT_PATH}\", \"commit_ref_name\":\"${CI_COMMIT_REF_NAME}\", \"commit_ref_slug\":\"${CI_COMMIT_REF_SLUG}\", \"commit_sha\":\"${CI_COMMIT_SHA}\", \"pipeline_url\":\"${CI_PIPELINE_URL}\", \"packaged\":\"${timestamp}\"}}" > .version
 
   artifacts:
     paths:
-    - ./*
-    #- ./*.js
-    #- ./*/*.lzma
-    #- ./.version
+      - ./*
+
+
+hybrixd:
+  cache: {}
+  stage: build-hybrixd
+  services:
+    - docker:stable-dind
+  script:
+  # Install JQ dependency
+  - apt-get update
+  - apt-get -y install jq
+
+  - WORKING_DIR=$PWD
+  - echo $PWD
+
+  # remove existing files and unzip the downloaded artifact to the directory (|| true --> on error, no problem)
+  - rm -rf  *
+
+  # download [hybrixd] artifact (workaround to get the latest artifact)
+  - PROJECT_REF_SLUG=hybrix%2Fhybrixd%2Fnode
+  - PROJECT_REF_PATH=hybrix/hybrixd/node
+  - PROJECT_REF_NAME=hybrixd
+  - PROJECT_REF_BRANCH=master
+  - "RESPONSE=$(curl --header \"Private-Token: $PRIVATE_TOKEN\" --silent \"https://gitlab.com/api/v4/projects/${PROJECT_REF_SLUG}/jobs?scope=success\")"
+  - "echo \"${RESPONSE}\" | jq -r 'first(.[] | select(.name == \"hybrixd\" and .ref == \"master\")) | .id'"
+  - "BUILD_JOB_ID=$(echo \"${RESPONSE}\" | jq -r 'first(.[] | select(.name == \"hybrixd\" and .ref == \"master\")) | .id')"
+  - "echo \"Downloading the artifact from: https://gitlab.com/${PROJECT_REF_PATH}/-/jobs/${BUILD_JOB_ID}/artifacts/download\""
+  - "curl --location --header \"Private-Token: $PRIVATE_TOKEN\" \"https://gitlab.com/api/v4/projects/${PROJECT_REF_SLUG}/jobs/${BUILD_JOB_ID}/artifacts\" -o artifacts-${PROJECT_REF_NAME}.zip"
+
+  - unzip -o artifacts-hybrixd.zip -d ./
+
+  # remove the zip-file (|| true --> on error, no problem)
+  - rm -rf  artifacts-hybrixd.zip
+
+  # Get Deterministic artifact
+  - PROJECT_REF_SLUG=hybrix%2Fhybrixd%2Fclient%2Fmodules%2Fdeterministic
+  - PROJECT_REF_PATH=hybrix/hybrixd/client/modules/deterministic
+  - PROJECT_REF_NAME=deterministic
+  - PROJECT_REF_BRANCH=master
+  - "RESPONSE=$(curl --header \"Private-Token: $PRIVATE_TOKEN\" --silent \"https://gitlab.com/api/v4/projects/${PROJECT_REF_SLUG}/jobs?scope=success\")"
+  - "BUILD_JOB_ID=$(echo \"${RESPONSE}\" | jq -r 'first(.[] | select(.name == \"deterministic\")) | .id')"
+  - "curl --location --header \"Private-Token: $PRIVATE_TOKEN\" \"https://gitlab.com/api/v4/projects/${PROJECT_REF_SLUG}/jobs/${BUILD_JOB_ID}/artifacts\" -o artifacts-${PROJECT_REF_NAME}.zip"
+
+  # unzip the downloaded artifact to the directory
+  - unzip -o artifacts-deterministic.zip -d artifacts-deterministic/
+  - rm -rf modules/deterministic
+  - cp -rf artifacts-deterministic/ ./deterministic/
+
+  # remove the unzipped-files and the zip-file (|| true --> on error, no problem)
+  - rm -rf  artifacts-deterministic
+  - rm -rf  artifacts-deterministic.zip
+
+  # remove .git files from artifact
+  - rm -rf ./.git*
+  # -------
+
+  # concatenate all .version files in the package
+  - "find . -name \".version\" -print | xargs cat | tr '\n' ' ' | sed 's:} {:,:g' > versions.json"
+  - "rm -rf .version"
+
+  # prettify json in .versions
+  - echo "const util = require('util'); const fs = require('fs'); var obj = JSON.parse(fs.readFileSync('versions.json', 'utf8')); const fs_writeFile = util.promisify(fs.writeFile); const fs_readFile = util.promisify(fs.readFile); fs_writeFile('versions.json', JSON.stringify(obj, null, 4));" > prettify.js
+  - node prettify.js && rm prettify.js
+
+  - cd $WORKING_DIR
+  - service docker start
+  - sleep 20s
+  - setup_docker
+  - sleep 20s
+  - build
+  artifacts:
+    paths:
+      - ./*
+
+test:
+  stage: test
+  script:
+    - mv ./deterministic ./modules/deterministic
+    - echo | cat ./hybrixd.conf
+    - echo | cat ./scripts/pipeline/test.sh
+    - sh ./scripts/pipeline/test.sh
+  coverage: /SUCCESS RATE[^|]*\:[^|]*\s+([\d\.]+)/
+  dependencies:
+    - hybrixd
+    - deterministic
+  except:
+   refs:
+     - tags
+  artifacts:
+    reports:
+      junit: test*.xml
+
+# ---------------------------------------------------------------------------
+
+.auto_devops: &auto_devops |
+  # Auto DevOps variables and functions
+  [[ "$TRACE" ]] && set -x
+  export DATABASE_URL=${DATABASE_URL-$auto_database_url}
+  export CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
+  export CI_APPLICATION_TAG=$CI_COMMIT_SHA
+  export CI_CONTAINER_NAME=ci_job_build_${CI_JOB_ID}
+  export TILLER_NAMESPACE=$KUBE_NAMESPACE
+  # Extract "MAJOR.MINOR" from CI_SERVER_VERSION and generate "MAJOR-MINOR-stable" for Security Products
+  export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
+
+  function init() {
+    apt-get update
+
+    apt-get install unzip
+
+    npm install -g jsdoc
+
+    # download common repo
+    curl --location --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/hybrix%2Fhybrixd%2Fcommon/jobs/artifacts/master/download?job=common" -o artifacts-common.zip
+
+    # remove link to common and unzip the downloaded artifact to the directory (|| true --> on error, no problem)
+    rm -rf  common || true
+    unzip -o artifacts-common.zip -d common
+
+    # remove the zip-file (|| true --> on error, no problem)
+    rm -rf  artifacts-common.zip || true
+
+    # remove symbolic link to node
+    rm -rf  node || true
+    # don't download git clone https://github.com/internetofcoins/nodejs-v8-lts.git, refer to docker pre installed nodejs as defined in the first line of this file
+    ln -s "$(which nodejs)" node
+  }
+
+  function registry_login() {
+    if [[ -n "$CI_REGISTRY_USER" ]]; then
+      echo "Logging to GitLab Container Registry with CI credentials..."
+      docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
+      echo ""
+    fi
+  }
+
+  function get_replicas() {
+    track="${1:-stable}"
+    percentage="${2:-100}"
+
+    env_track=$( echo $track | tr -s  '[:lower:]'  '[:upper:]' )
+    env_slug=$( echo ${CI_ENVIRONMENT_SLUG//-/_} | tr -s  '[:lower:]'  '[:upper:]' )
+
+    if [[ "$track" == "stable" ]] || [[ "$track" == "rollout" ]]; then
+      # for stable track get number of replicas from `PRODUCTION_REPLICAS`
+      eval new_replicas=\$${env_slug}_REPLICAS
+      if [[ -z "$new_replicas" ]]; then
+        new_replicas=$REPLICAS
+      fi
+    else
+      # for all tracks get number of replicas from `CANARY_PRODUCTION_REPLICAS`
+      eval new_replicas=\$${env_track}_${env_slug}_REPLICAS
+      if [[ -z "$new_replicas" ]]; then
+        eval new_replicas=\${env_track}_REPLICAS
+      fi
+    fi
+
+    replicas="${new_replicas:-1}"
+    replicas="$(($replicas * $percentage / 100))"
+
+    # always return at least one replicas
+    if [[ $replicas -gt 0 ]]; then
+      echo "$replicas"
+    else
+      echo 1
+    fi
+  }
+
+  function deploy() {
+    track="${1-stable}"
+    percentage="${2:-100}"
+    name="$CI_ENVIRONMENT_SLUG"
+
+    replicas="1"
+    service_enabled="true"
+    postgres_enabled="$POSTGRES_ENABLED"
+
+    # if track is different than stable,
+    # re-use all attached resources
+    if [[ "$track" != "stable" ]]; then
+      name="$name-$track"
+      service_enabled="false"
+      postgres_enabled="false"
+    fi
+
+    replicas=$(get_replicas "$track" "$percentage")
+
+    if [[ "$CI_PROJECT_VISIBILITY" != "public" ]]; then
+      secret_name='gitlab-registry'
+    else
+      secret_name=''
+    fi
+
+    helm upgrade --install \
+      --wait \
+      --set service.enabled="$service_enabled" \
+      --set releaseOverride="$CI_ENVIRONMENT_SLUG" \
+      --set image.repository="$CI_APPLICATION_REPOSITORY" \
+      --set image.tag="$CI_APPLICATION_TAG" \
+      --set image.pullPolicy=IfNotPresent \
+      --set image.secrets[0].name="$secret_name" \
+      --set application.track="$track" \
+      --set application.database_url="$DATABASE_URL" \
+      --set service.url="$CI_ENVIRONMENT_URL" \
+      --set replicaCount="$replicas" \
+      --set postgresql.enabled="$postgres_enabled" \
+      --set postgresql.nameOverride="postgres" \
+      --set postgresql.postgresUser="$POSTGRES_USER" \
+      --set postgresql.postgresPassword="$POSTGRES_PASSWORD" \
+      --set postgresql.postgresDatabase="$POSTGRES_DB" \
+      --namespace="$KUBE_NAMESPACE" \
+      --version="$CI_PIPELINE_ID-$CI_JOB_ID" \
+      "$name" \
+      chart/
+
+    kubectl rollout status -n "$KUBE_NAMESPACE" -w "deployment/$name"
+  }
+
+  function setup_docker() {
+    if ! docker info &>/dev/null; then
+      if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
+        export DOCKER_HOST='tcp://localhost:2375'
+      fi
+    fi
+  }
+
+  function download_chart() {
+    if [[ ! -d chart ]]; then
+      auto_chart=${AUTO_DEVOPS_CHART:-gitlab/auto-deploy-app}
+      auto_chart_name=$(basename $auto_chart)
+      auto_chart_name=${auto_chart_name%.tgz}
+      auto_chart_name=${auto_chart_name%.tar.gz}
+    else
+      auto_chart="chart"
+      auto_chart_name="chart"
+    fi
+
+    helm init --client-only
+    helm repo add gitlab https://charts.gitlab.io
+    if [[ ! -d "$auto_chart" ]]; then
+      helm fetch ${auto_chart} --untar
+    fi
+    if [ "$auto_chart_name" != "chart" ]; then
+      mv ${auto_chart_name} chart
+    fi
+
+    helm dependency update chart/
+    helm dependency build chart/
+  }
+
+  function ensure_namespace() {
+    kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
+  }
+
+  function check_kube_domain() {
+    if [ -z ${AUTO_DEVOPS_DOMAIN+x} ]; then
+      echo "In order to deploy or use Review Apps, AUTO_DEVOPS_DOMAIN variable must be set"
+      echo "You can do it in Auto DevOps project settings or defining a variable at group or project level"
+      echo "You can also manually add it in .gitlab-ci.yml"
+      false
+    else
+      true
+    fi
+  }
+
+  function build() {
+    registry_login
+
+    if [[ -f Dockerfile ]]; then
+      echo "Building Dockerfile-based application..."
+      docker build \
+        --build-arg HTTP_PROXY="$HTTP_PROXY" \
+        --build-arg http_proxy="$http_proxy" \
+        --build-arg HTTPS_PROXY="$HTTPS_PROXY" \
+        --build-arg https_proxy="$https_proxy" \
+        --build-arg FTP_PROXY="$FTP_PROXY" \
+        --build-arg ftp_proxy="$ftp_proxy" \
+        --build-arg NO_PROXY="$NO_PROXY" \
+        --build-arg no_proxy="$no_proxy" \
+        -t "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" .
+    else
+      echo "Building Heroku-based application using gliderlabs/herokuish docker image..."
+
+      echo "------"
+      echo "$(pwd)"
+      echo "$CI_CONTAINER_NAME"
+      echo "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
+      echo "------"
+
+      docker run -i \
+        -e BUILDPACK_URL \
+        -e HTTP_PROXY \
+        -e http_proxy \
+        -e HTTPS_PROXY \
+        -e https_proxy \
+        -e FTP_PROXY \
+        -e ftp_proxy \
+        -e NO_PROXY \
+        -e no_proxy \
+        --name="$CI_CONTAINER_NAME" -v "$(pwd):/tmp/app:ro" gliderlabs/herokuish /bin/herokuish buildpack build
+      docker commit "$CI_CONTAINER_NAME" "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
+      docker rm "$CI_CONTAINER_NAME" >/dev/null
+      echo ""
+
+      echo "Configuring $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG docker image..."
+      docker create --expose 5000 --env PORT=5000 --name="$CI_CONTAINER_NAME" "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" /bin/herokuish procfile start web
+
+      # replace port for api root (1111) with 5000 in config
+      sed -i -e "s#1111#5000#g" hybrixd.conf
+      # replace /root with empty string in config
+      sed -i -e "s#\"/root\"#\"\"#g" hybrixd.conf
+      cat hybrixd.conf
+
+      # replace 127.0.0.1 with $POD_IP on start
+      sed -i -e "s:\"./hybrixd\":\"sed -i -e 's/127.0.0.1/'\$POD_IP'/g' hybrixd.conf \&\& ./hybrixd\":g" package.json
+
+      docker cp hybrixd.conf "$CI_CONTAINER_NAME":/app/hybrixd.conf
+      docker cp package.json "$CI_CONTAINER_NAME":/app/package.json
+
+      #END CUSTOM SCRIPT
+
+      docker commit "$CI_CONTAINER_NAME" "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
+      docker rm "$CI_CONTAINER_NAME" >/dev/null
+      echo ""
+    fi
+
+    echo "Pushing to GitLab Container Registry..."
+    docker push "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
+    echo ""
+  }
+
+  function install_tiller() {
+    echo "Checking Tiller..."
+    helm init --upgrade
+    kubectl rollout status -n "$TILLER_NAMESPACE" -w "deployment/tiller-deploy"
+    if ! helm version --debug; then
+      echo "Failed to init Tiller."
+      return 1
+    fi
+    echo ""
+  }
+
+  function create_secret() {
+    echo "Create secret..."
+    if [[ "$CI_PROJECT_VISIBILITY" == "public" ]]; then
+      return
+    fi
+
+    kubectl create secret -n "$KUBE_NAMESPACE" \
+      docker-registry gitlab-registry \
+      --docker-server="$CI_REGISTRY" \
+      --docker-username="${CI_DEPLOY_USER:-$CI_REGISTRY_USER}" \
+      --docker-password="${CI_DEPLOY_PASSWORD:-$CI_REGISTRY_PASSWORD}" \
+      --docker-email="$GITLAB_USER_EMAIL" \
+      -o yaml --dry-run | kubectl replace -n "$KUBE_NAMESPACE" --force -f -
+  }
+
+  function persist_environment_url() {
+      echo $CI_ENVIRONMENT_URL > environment_url.txt
+  }
+
+  function delete() {
+    track="${1-stable}"
+    name="$CI_ENVIRONMENT_SLUG"
+
+    if [[ "$track" != "stable" ]]; then
+      name="$name-$track"
+    fi
+
+    if [[ -n "$(helm ls -q "^$name$")" ]]; then
+      helm delete --purge "$name"
+    fi
+  }
+
+  function dist() {
+    # clean up and prepare the artifacts (instead of having a dist)
+    mv ./dist/* ./
+    rm -rf ./dist || true
+
+    # remove .git directory and .* files
+    rm -rf ./.git* || true
+  }
+
+before_script:
+  - *auto_devops
